version: '3.8'

volumes:
# create colume db-data for postgres
  db-data:
    driver: local

networks:
  backend:

services:
  app:
    image: mcr.microsoft.com/devcontainers/go:0-1.19-buster
    environment:
      - DATABASE_URL="postgres://postgres:postgres@db:5432/postgres"
      - PORT=80
    ports:
      - 18080:80
    networks:
      - backend
    #command installs the go dependencies and then overrites the entrypoint to run the app
    command: ["bash", "-c", "while sleep 1000; do :; done"]

  db:
    image: timescale/timescaledb-ha:pg14-ts2.8-latest
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TIMESCALEDB_TELEMETRY=off
    networks:
      - backend